name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    

jobs:
  flutter_test:
    name: Run flutter test and analyze
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1    

      # Run installation on dependencies
      - name: install dependencies
        run: flutter pub get

      # Runs code analyzer
      - name: run analyze
        run: flutter analyze

      # Runs tests
      - name: run test
        run: flutter test 
